import string

LOCALE_CODES_MAP = {
    "ru_RU": "RU",
    "en_US": "EN",
    "en_GB": "EN",
    "pt_BR": "PT-BR",
    "kz_KZ": "KK",
    "de-DE": "de",
    "it-IT": "it",
    "fr-FR": "fr",
}

ALPHABET_DE = "ÄäÖöÜüẞß"
ALPHABET_ES = "áéíóúüñ"
ALPHABET_KK = "ӘәҒғҢңҚқӨөҰұҮүҺһІі"
ALPHABET_UZ = "ҒғЎўҚқҲҳʻ"

PUNCTUATION_DASH = r"\-\—"

PUNCTUATION_LEFT = r"(" + PUNCTUATION_DASH

PUNCTUATION_RIGHT = r".:;!?)"

PUNCTUATION = r"\"\+," + PUNCTUATION_LEFT + PUNCTUATION_RIGHT
PUNCTUATION_EXTEND = PUNCTUATION + "«»'ʼ"
PUNCTUATION_ALL = string.punctuation + PUNCTUATION_EXTEND

UNIVERSAL_POS = [
    "ADJ",
    "ADP",
    "ADV",
    "AUX",
    "CCONJ",
    "DET",
    "INTJ",
    "NOUN",
    "NUM",
    "PART",
    "PRON",
    "PROPN",
    "PUNCT",
    "SCONJ",
    "SYM",
    "VERB",
    "X",
]

REL_NATASHA = [
    "<pad>",
    "acl",
    "acl:relcl",
    "advcl",
    "advmod",
    "amod",
    "appos",
    "aux",
    "aux:pass",
    "case",
    "cc",
    "ccomp",
    "compound",
    "conj",
    "cop",
    "csubj",
    "csubj:pass",
    "dep",
    "det",
    "det:poss",
    "discourse",
    "dislocated",
    "expl",
    "expl:pass",
    "expl:impers",
    "expl:pv",
    "fixed",
    "flat",
    "flat:foreign",
    "flat:name",
    "goeswith",
    "iobj",
    "list",
    "mark",
    "nmod",
    "nsubj",
    "nsubj:pass",
    "nummod",
    "nummod:entity",
    "nummod:gov",
    "obj",
    "obl",
    "obl:agent",
    "orphan",
    "parataxis",
    "parataxis:obj",
    "parataxis:hashtag",
    "punct",
    "root",
    "vocative",
    "xcomp",
    "x",
]

REL_STANZA = [
    "nsubj",
    "nsubj:pass",
    "nsubj:outer",
    "csubj",
    "csubj:pass",
    "csubj:outer",
    "obj",
    "ccomp",
    "xcomp",
    "iobj",
    "advcl",
    "advcl:relcl",
    "advmod",
    "nmod",
    "neg",
    "nmod:npmod",
    "nmod:tmod",
    "nmod:poss",
    "vocative",
    "aux",
    "aux:pass",
    "mark",
    "discourse",
    "discourse:emo",
    "punct",
    "expl",
    "expl:pass",
    "expl:impers",
    "expl:pv",
    "cop",
    "nummod",
    "nummod:entity",
    "nummod:gov",
    "acl",
    "acl:relcl",
    "amod",
    "appos",
    "det",
    "det:poss",
    "det:predet",
    "compound",
    "fixed",
    "goeswith",
    "compound:prt",
    "flat",
    "flat:foreign",
    "flat:name",
    "foreign",
    "conj",
    "cc",
    "cc:preconj",
    "case",
    "list",
    "parataxis",
    "orphan",
    "dislocated",
    "reparandum",
    "root",
    "dep",
    "obl",
    "obl:agent",
    "obl:tmod",
    "obl:arg",
    "obl:npmod",
    "x",
]

INTONATION_TYPES = {
    0: "quest_type0",  # вопросительное предложение без дополнительной разметки
    1: "quest_type1",  # специальный вопрос с вопросительным словом или частицей 'ли', 'неужели': Как #ты это делаешь?
    2: "quest_type2",  # специальный вопрос с придаточным: Кто может сказать, что такое #настоящая дружба?
    3: "quest_type3",  # общий вопрос с ударением на последнем слове: Этот вид рыб плавает в #океане?
    4: "quest_type4",  # вопрос с или: У вас #карта или #наличные?
    5: "quest_type5",  # общий вопрос с переходом ударением: Ники+та #сможет проделать работу хорошо?
    6: "quest_type6",
    7: "quest_type7",  # вопрос, начинающийся со слова 'А': А #как это называется на английском?
    ".": "dot_type",  # утвердительное предложение
    "!": "excl_type",  # восклицательное предложение
    "?": "quest_type0",  # вопросительное предложение
}

PHONEMES_ENGLISH = [
    "AA0",
    "AA1",
    "AA2",
    "AE0",
    "AE1",
    "AE2",
    "AH0",
    "AH1",
    "AH2",
    "AO0",
    "AO1",
    "AO2",
    "AW0",
    "AW1",
    "AW2",
    "AY0",
    "AY1",
    "AY2",
    "B",
    "CH",
    "D",
    "DH",
    "EH0",
    "EH1",
    "EH2",
    "ER0",
    "ER1",
    "ER2",
    "EY0",
    "EY1",
    "EY2",
    "F",
    "G",
    "HH",
    "IH0",
    "IH1",
    "IH2",
    "IY0",
    "IY1",
    "IY2",
    "JH",
    "K",
    "L",
    "M",
    "N",
    "NG",
    "OW0",
    "OW1",
    "OW2",
    "OY0",
    "OY1",
    "OY2",
    "P",
    "R",
    "S",
    "SH",
    "T",
    "TH",
    "UH0",
    "UH1",
    "UH2",
    "UW",
    "UW0",
    "UW1",
    "UW2",
    "V",
    "W",
    "Y",
    "Z",
    "ZH",
]

PHONEMES_IPA = [
    "e̞",
    "i",
    "y",
    "ɨ",
    "ʉ",
    "ɯ",
    "u",
    "ɪ",
    "ʏ",
    "ʊ",
    "e",
    "ø",
    "ɘ",
    "ɵ",
    "ɤ",
    "o",
    "ɛ",
    "œ",
    "ɜ",
    "ɞ",
    "ʌ",
    "ɔ",
    "æ",
    "ɐ",
    "a",
    "ɶ",
    "ɑ",
    "ɒ",
    "m",
    "ɱ",
    "n",
    "ɳ",
    "ŋ",
    "ɴ",
    "p",
    "b",
    "t",
    "d",
    "ʈ",
    "ɖ",
    "c",
    "ɟ",
    "k",
    "ɡ",
    "g",
    "q",
    "ɢ",
    "ʡ",
    "ʔ",
    "ɸ",
    "β",
    "f",
    "v",
    "θ",
    "ð",
    "s",
    "z",
    "ʃ",
    "ʒ",
    "ʂ",
    "ʐ",
    "ç",
    "x",
    "ɣ",
    "χ",
    "ʁ",
    "ħ",
    "h",
    "ɦ",
    "w",
    "ʋ",
    "ɹ",
    "ɻ",
    "j",
    "ɰ",
    "ⱱ",
    "ɾ",
    "ɽ",
    "ʙ",
    "r",
    "ʀ",
    "l",
    "ɫ",
    "ɭ",
    "ʎ",
    "ʟ",
    "ə",
    "ɚ",
    "ɝ",
    "ɹ",
    "ɕ",
    "ʑ",
    "ɲ",
    "ʝ",
    "ʲ",
    "1",
    "ˈ",
    "ˌ",
    "ː",
    "“",
    "̪",
    "'",
    " ",
    "̃",
    "S",
    "[",
]

EN2IPA = {
    "AA": "ɑ",
    "AE": "æ",
    "AH": "ʌ",
    "AO": "ɔ",
    "AW": ("a", "ʊ"),
    "AX": "ə",
    "AXR": "ɚ",
    "AY": ("a", "ɪ"),
    "EH": "ɛ",
    "ER": "ɝ",
    "EY": ("e", "ɪ"),
    "IH": "ɪ",
    "IX": "ɨ",
    "IY": "i",
    "OW": ("o", "ʊ"),
    "OY": ("ɔ", "ɪ"),
    "UH": "ʊ",
    "UW": "u",
    "UX": "ʉ",
    "B": "b",
    "CH": ("t", "ʃ"),
    "D": "d",
    "DH": "ð",
    "DX": "ɾ",
    "EL": "l̩",
    "EM": "m̩",
    "EN": "n̩",
    "F": "f",
    "G": "ɡ",
    "HH": "h",
    "JH": ("d", "ʒ"),
    "K": "k",
    "L": "l",
    "M": "m",
    "N": "n",
    "NG": "ŋ",
    "P": "p",
    "Q": "ʔ",
    "R": "ɹ",
    "S": "s",
    "SH": "ʃ",
    "T": "t",
    "TH": "θ",
    "V": "v",
    "W": "w",
    "WH": "ʍ",
    "Y": "j",
    "Z": "z",
    "ZH": "ʒ",
    "AA0": "ɑ",
    "AE0": "æ",
    "AH0": "ʌ",
    "AO0": "ɔ",
    "AW0": ("a", "ʊ"),
    "AX0": "ə",
    "AXR0": "ɚ",
    "AY0": ("a", "ɪ"),
    "EH0": "ɛ",
    "ER0": "ɝ",
    "EY0": ("e", "ɪ"),
    "IH0": "ɪ",
    "IX0": "ɨ",
    "IY0": "i",
    "OW0": ("o", "ʊ"),
    "OY0": ("ɔ", "ɪ"),
    "UH0": "ʊ",
    "UW0": "u",
    "UX0": "ʉ",
    "AA1": ("ˈ", "ɑ"),
    "AE1": ("ˈ", "æ"),
    "AH1": ("ˈ", "ʌ"),
    "AO1": ("ˈ", "ɔ"),
    "AW1": ("ˈ", "a", "ʊ"),
    "AX1": ("ˈ", "ə"),
    "AXR1": ("ˈ", "ɚ"),
    "AY1": ("ˈ", "a", "ɪ"),
    "EH1": ("ˈ", "ɛ"),
    "ER1": ("ˈ", "ɝ"),
    "EY1": ("ˈ", "e", "ɪ"),
    "IH1": ("ˈ", "ɪ"),
    "IX1": ("ˈ", "ɨ"),
    "IY1": ("ˈ", "i"),
    "OW1": ("ˈ", "o", "ʊ"),
    "OY1": ("ˈ", "ɔ", "ɪ"),
    "UH1": ("ˈ", "ʊ"),
    "UW1": ("ˈ", "u"),
    "UX1": ("ˈ", "ʉ"),
    "AA2": ("ˌ", "ɑ"),
    "AE2": ("ˌ", "æ"),
    "AH2": ("ˌ", "ʌ"),
    "AO2": ("ˌ", "ɔ"),
    "AW2": ("ˌ", "a", "ʊ"),
    "AX2": ("ˌ", "ə"),
    "AXR2": ("ˌ", "ɚ"),
    "AY2": ("ˌ", "a", "ɪ"),
    "EH2": ("ˌ", "ɛ"),
    "ER2": ("ˌ", "ɝ"),
    "EY2": ("ˌ", "e", "ɪ"),
    "IH2": ("ˌ", "ɪ"),
    "IX2": ("ˌ", "ɨ"),
    "IY2": ("ˌ", "i"),
    "OW2": ("ˌ", "o", "ʊ"),
    "OY2": ("ˌ", "ɔ", "ɪ"),
    "UH2": ("ˌ", "ʊ"),
    "UW2": ("ˌ", "u"),
    "UX2": ("ˌ", "ʉ"),
}

RU2IPA = {
    "K": "k",
    "KH": "x",
    "GH": "ɣ",
    "G": "g",
    "SH": "ʂ",
    "ZH": "ʐ",
    "DZ": ("d", "z"),
    "DZH": ("d", "ʑ", "h"),
    "R": "r",
    "T": "t",
    "TS": ("t", "s"),
    "S": "s",
    "D": "d",
    "Z": "z",
    "N": "n",
    "L": "ɫ",
    "P": "p",
    "F": "f",
    "B": "b",
    "V": "v",
    "M": "m",
    "K0": ("k", "ʲ"),
    "KH0": ("x", "ʲ"),
    "GH0": ("ɣ", "ʲ"),
    "G0": ("g", "ʲ"),
    "J0": "j",
    "TSH0": ("t", "ɕ"),
    "SH0": ("ɕ", "ː"),
    "ZH0": ("ʑ", "ː"),
    "DZ0": ("d", "z", "ʲ"),
    "DZH0": ("s", "ʑ", "h", "ʲ"),
    "R0": ("r", "ʲ"),
    "T0": ("t", "ʲ"),
    "TS0": ("t", "s", "ʲ"),
    "S0": ("s", "ʲ"),
    "D0": ("d", "ʲ"),
    "Z0": ("z", "ʲ"),
    "N0": ("n", "ʲ"),
    "L0": ("l", "ʲ"),
    "P0": ("p", "ʲ"),
    "F0": ("f", "ʲ"),
    "B0": ("b", "ʲ"),
    "V0": ("v", "ʲ"),
    "M0": ("m", "ʲ"),
    "U": "u",
    "O": "o",
    "A": "a",
    "E": "e̞",
    "Y": "ɨ",
    "I": "i",
    "U0": ("ˈ", "u"),
    "O0": ("ˈ", "o"),
    "A0": ("ˈ", "a"),
    "E0": ("ˈ", "e̞"),
    "Y0": ("ˈ", "ɨ"),
    "I0": ("ˈ", "i"),
    "Ul": ("u", "ː"),
    "Ol": ("o", "ː"),
    "Al": ("a", "ː"),
    "El": ("e̞", "ː"),
    "Yl": ("ɨ", "ː"),
    "Il": ("i", "ː"),
    "U0l": ("ˈ", "u", "ː"),
    "O0l": ("ˈ", "o", "ː"),
    "A0l": ("ˈ", "a", "ː"),
    "E0l": ("ˈ", "e̞", "ː"),
    "Y0l": ("ˈ", "ɨ", "ː"),
    "I0l": ("ˈ", "i", "ː"),
}

ALLOWED_SSML_TAGS = {
    "seed",
    "audio",
    "break",
    "breath",
    "emphasis",
    "options",
    "p",
    "prosody",
    "s",
    "say-as",
    "style",
    "sub",
    "volume",
    "phoneme",
    "intonation",
}
